### ISSUE TITLE
ApproximateDateField Django 2.2 Migration Generates TypeError

### ISSUE THREAD

**Issue by jplehmann** [dracos/django-date-extensions#23]
After upgrading to Django 2.2, I noticed I needed to generate some migrations.   Note I was using version 2 of this library until just now, but upgrading to 3 didn't seem to help.

My model uses the field as follows:
```
dob = ApproximateDateField(default="", blank=True)
```
The migration created is:
```
    operations = [
        migrations.AlterField(
            model_name='snake',
            name='dob',
            field=django_date_extensions.fields.ApproximateDateField(blank=True, default=''),
        ),
    ]
```

When trying to migrate, I get the following error:
```
Traceback (most recent call last):
  File "./manage.py", line 27, in <module>
    raise e
  File "./manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/core/management/commands/sqlmigrate.py", line 30, in execute
    return super().execute(*args, **options)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/core/management/commands/sqlmigrate.py", line 64, in handle
    sql_statements = executor.collect_sql(plan)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/migrations/executor.py", line 225, in collect_sql
    state = migration.apply(state, schema_editor, collect_sql=True)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 249, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 535, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/backends/postgresql/schema.py", line 124, in _alter_field
    new_db_params, strict,
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 648, in _alter_field
    old_default = self.effective_default(old_field)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 233, in effective_default
    return field.get_db_prep_save(self._effective_default(field), self.connection)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 793, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 788, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/Users/john/.venv/mm/lib/python3.7/site-packages/django_date_extensions/fields.py", line 146, in get_prep_value
    if not ansi_date_re.search(value):
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by dracos** [comment]
Sorry to hear that, and the delay in replying.

I'm not sure what could be happening - is it possible your previous migration was generated under python 2, without importing unicode literals in your model, and therefore your migration file has b'' as the default for the field? And then you've upgraded to python3, django 2.2, and so now unicode is the default and so it's creating a migration to switch the default to '', but the code in python3 now does not like the byte literal from the migration before? Thinking of tickets like https://code.djangoproject.com/ticket/23226 - not the same, but I wonder if it's the same cause.

I've just created a new project, and the migration seems to have worked fine. It's quite possible there is a bug in the code somewhere, don't get me wrong, but I'm not sure what it could be from what you've provided, sorry.

**Comment by dracos** [comment]
(If that is the issue, you should be able to alter your migration files to remove the `b` and that should be fine as suggested at the end of that ticket I link to.)

**Comment by dracos** [comment]
As workarounds, I could change `if value in (None, ''):` to `if value in (None, u'', b''):` - or indeed `if not value`. I guess, that can't hurt, as far as I can tell, and would allow migrations like this to continue successfully anyway.

**Comment by dracos** [comment]
This is done, in version 3.1 just released. Hopefully that might help, if I have got any of the above right, anyway!

**Comment by jplehmann** [comment]
@dracos thanks for the thorough follow-up.  I believe I did go through and try to update past migrations as I recall.  I am not sure I'm having this issue any longer, so I'm going to close this but if I see it again I'll follow up.  Thanks!!
